# Generated by Django 5.0.2 on 2024-02-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "projectType",
                    models.CharField(
                        choices=[
                            ("Personal Project", "Personal Project"),
                            ("Internship Project", "Internship"),
                            ("Academic Project", "Academic Projects"),
                            ("Freelancing Project", "Freelance Project"),
                            ("Case Studies", "Case Study"),
                        ],
                        default="Personal Project",
                    ),
                ),
                ("aim", models.TextField(max_length=200, null=True)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                ("image", models.ImageField(upload_to="images/")),
                ("Description", models.TextField(max_length=500)),
            ],
        ),
    ]
