# Generated by Django 5.0.2 on 2024-02-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_url",
            field=models.URLField(null=True),
        ),
    ]
