# Generated by Django 5.0.2 on 2024-02-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile1", "0002_project_project_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("description", models.TextField(max_length=500)),
            ],
        ),
    ]
