# Generated by Django 5.0.1 on 2024-02-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile1", "0003_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("companyTitle", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                (
                    "jobType",
                    models.CharField(
                        choices=[
                            ("Internship", "Intern ship"),
                            ("Full Time", "FUll Time"),
                            ("Part Time", "Part Time"),
                            ("Contract", "Contract"),
                            ("Freelance", "Freelance"),
                        ],
                        default="Full Time",
                    ),
                ),
                ("jobDescription", models.TextField(max_length=1000)),
                (
                    "projects",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile1.project",
                    ),
                ),
            ],
        ),
    ]
