# Generated by Django 5.0.1 on 2024-02-22 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile1", "0004_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="projects",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profile1.project",
            ),
        ),
    ]
