# Generated by Django 5.0.1 on 2024-02-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile1", "0007_blog_category_blog_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(max_length=1000),
        ),
    ]
